### ISSUE TITLE
autogen.sh does not fail if it can't compile the extension

### ISSUE THREAD

**Issue by andreasscherbaum** [EnterpriseDB/mongo_fdw#150] opened 2021-06-07 20:02 UTC
```
./autogen.sh: line 69: cmake3: command not found
make: *** No rule to make target 'install'.  Stop.
Done
```
But the script does not break, or return a proper RC. Instead it returns 0 and acts like nothing happened.
This is against the UNIX philosophy, and it makes debugging hard, and building packages complicated.

**Comment by vaibhavdalvi93** [comment] 2021-06-09 03:08
Thanks @andreasscherbaum for writing to us.

First of all, can you please provide OS and it's version where you are facing this issue?

Why do you think _"cmake3: command not found"_  is not a proper error message? which is generated by operating system which clearly indicated that cmake3 is missing.

I am NOT denying your proposal but I want more thoughts on this.

**Comment by andreasscherbaum** [comment] 2021-06-09 06:21
The problem is not that _"cmake3: command not found"_ is not a proper error message. The problem is that this does not fail the script.

Let me illustrate this for you:
https://github.com/andreasscherbaum/mongo_fdw/runs/2780785418?check_suite_focus=true
I made this build fail because I removed the workaround I added for _cmake3_. And then I stopped the Workflow right after _autogen.sh_. If you open the log, select the "Configure the extension" part, and scroll all the way down to the end, I added an _"echo $?"_ there, to show the RC of the _autogen.sh_ script. It's "0", even though moments before the script failed because _cmake3_ could not be found.

By convention, if things are working, RC=0 is returned. If something is not working, RC is supposed to be != 0.

As a consequence, the GH Actions Workflow assumes everything is alright, because _autogen.sh_ does return RC=0. Otherwise the Workflow would fail right there. And it must fail, because of the _cmake3_ error.

**Comment by vaibhavdalvi93** [comment] 2021-06-16 02:14
@andreasscherbaum, can you please check if this issue is being fixed at your end or not?

It would be good to close this ticket if this is being fixed.

Thanks,
Vaibhav Dalvi

**Comment by andreasscherbaum** [comment] 2021-06-16 21:20
Can confirm it's working:

https://github.com/andreasscherbaum/mongo_fdw/runs/2843401419?check_suite_focus=true

This fails the build step, not the "Stop" step afterwards.

**Comment by jeevanchalke** [comment] 2022-06-10 09:39
Closing as the issue is fixed already.

**Closed by jeevanchalke** 2022-06-10 09:39 UTC
Labels: bug
